### ISSUE TITLE
update delay

### ISSUE THREAD

**Issue by alakader** [tdragon/reef-pi-hass-custom#11]
Hi
great effort and really easy to use, however i have an update delay issue, like when i turn on a switch though HA it lags on reef-pi side to be updated as turned on
the other way if i turn a switch on on reef-pi side it will not update on HA side for a long time even if i reload the page, the only solution is to open a different item other than Lovelace and then return to it
i tried to find an update option in the code but failed also i can not find an update option in HA Lovelace
any advice will be appreciated
regards

**Comment by tdragon** [comment]
The integration uses polling with 1 minute interval. 
When you toggle a switch from Home Assistant it asks HA to refresh the state, but there is still short delay. 
When reef-pi switches itself, there could be up to a minute delay before the change is reflected. 

I don't see how to improve these delays with the polling approach. 

It would be better to use MQTT, but reef-pi MQTT implementation doesn't support multiple instances.

**Comment by tdragon** [comment]
The polling interval is defined there: custom_components/reef_pi/__init__.py
Line 122

The update function is defined in the same file.

**Comment by alakader** [comment]
thanks for the quick response
i was trying to use MQTT-IO (https://github.com/flyte/mqtt-io) for this but found your integration during my search, if you would like to take a look at it it can help, for the delay of one minute will this affect automations, i mean if a sensor reading or float switch changes it will have to wait one min for this to be detected on HA side

**Comment by tdragon** [comment]
Thank you for the link. I'll take a look. 

The reef-pi is a controller by itself, it's better to use the built-in automation and not mix it with HA. 

The main goal for this integration is monitoring and exposing manual controls. For this purpose 1 minute delay is not critical.

**Comment by alakader** [comment]
the main problem with reef-pi is not having LOGIC functions as needed and it is not possible to implement them in the future as was stated by Ranjib, i want to use HA for some logic based automations for example when my ATO is near empty i want to receive email, if my sump water level goes up i need to change pump speed and so on

**Comment by tdragon** [comment]
In your case I would look into a custom configuration based on MQTT. It will provide real-time status from the reef-pi. 

You can still use my integration for controlling. I don't think it is possible to control reef-pi through MQTT.
