### ISSUE TITLE
pH Sensor value does not update

### ISSUE THREAD

**Issue by danmrossi** [tdragon/reef-pi-hass-custom#19]
Hi All 

Been using this addon for a few months now and would like to say well done to @tdragon - Would also like to say that the Macro Control works (i don't have an account yet on HA to reply to your thread there).

I shut-down my Reef-Pi and my Home Assistant Server (both on their own separate Raspberry Pi's)  as i had to move their power supplies and now the pH Sensor only updates the once upon HA Startup and thats it. Unless i reload the Reef-Pi HACS integration will it update one more time and then back to not updating at all. My 2 temp sensors update every few minutes or so without issue.

Reef-Pi is on v5.3 running on a robo-tank board with it's inbuilt pH Connector/Sensor - pH Graphs update every 60 seconds in reef-pi GUI without issue.

I have gone as far as deleting your addon, deleting HACS, Rebooting, clearing any leftovers and reinstalling. Still same thing. Even restored HA to a 2022.08.x backup. No change.

Home Assistant build is 2022.9.7, Supervisor is 2022.09.1, Frontend is 20220907.2, Operating System is 8.5
HACS build is: Integration 1.27.2, Frontend is 20220906112053

Also when i last updated Home Assistant and rebooted it, the ph Sensor worked as normal. I have also tried rebooting both devices in staggered but different orders, no change. Rebooted my WiFi router for the hell of it. No change.

Has anyone else experienced anything like this or know where i could start to try and figure out the cause/issue?

Is there any other things i can provide to assist in diagnosis?

Many thanks :)

Daniel

**Comment by danmrossi** [comment]
Also meant to add reef-pi 5.3 was installed about 4 days after it had came out, so makes it hard for me to attribute any changes made that could cause this annoying issue :)

**Comment by danmrossi** [comment]
i enabled debug logging for HA and HACS and rebooted and monitored, no errors of any kind to produce.

**Comment by tdragon** [comment]
This is strange: the code to update Ph and temperature is the same. The integration simple polls temperature and Ph periodically. 
The only way it won't get the Ph if ph capability reported as missing. 
Can you check debug logs of the integration, there should be "Fetching phprobes" when it gets ph?

**Comment by tdragon** [comment]
Also, could you open following pages and share results:

https://{ip of your reef pi}/api/capabilities
https://{ip of your reef pi}/api/phprobes

**Comment by danmrossi** [comment]
http://192.168.1.202/api/capabilities

{"dev_mode":false,"dashboard":true,"health_check":true,"equipment":true,"timers":true,"lighting":false,"temperature":true,"ato":false,"camera":false,"doser":false,"ph":true,"macro":true,"configuration":true,"journal":false}

http://192.168.1.202/api/phprobes

[{"id":"1","name":"pH","enable":true,"period":60,"analog_input":"1","control":false,"notify":{"enable":false,"min":0,"max":0},"upper_eq":"","downer_eq":"","min":0,"max":0,"hysteresis":0,"is_macro":false,"one_shot":false,"chart":{"ymin":5,"ymax":8,"color":"#1200ff","unit":"pH"},"transformer":""}]

Also, when it was working, it would take randomly anywhere from 3 up to 10 minutes to update either ph or temp values, is that normal?

Checked the debug logs and found the fetching phprobes area and it says it sees the probe, nothing errored.

**Comment by tdragon** [comment]
The query result seems to be correct.
How do you check the value in home assistant? Is it possible that Home Assistant created a new entity for Ph with new name and you are looking on old one?
You can check the list of entities in home assistant in "config/entities" page.

Home Assistant sees only changes of value, so if temperature doesn't change for 10 minutes it will show that it has been updated 10 minutes ago. The integration pools all values every minute.

**Comment by danmrossi** [comment]
im at work at the moment, i checked remotely and its the only sensor there in the config entities page, i just know that its not updating as i have another ph probe in the tank running off something else so i know the ph is going up/down as required. i clicked on it there and same thing doesn't show any updates, when i go to reload the reef-pi integration it updates that once to the new value and then nothing.

Just wondering, is it possible in your code to have it force update the value / last updated timestamp regardless of if its the same value?

When i get home from work hopefully tomorrow ill do a full backup and then rebuild HA from scratch since the reef-pi has its own dedicated one so wont take me long ;) and its been updated all the time since some 2021 build so probably about time i refresh it. Ill do the same with my reef-pi since being updated since v3ish from the top of my head.

I work in IT myself so i am thinking that this might be one of those pesky issues from some hidden cache i havent found yet lol

**Comment by tdragon** [comment]
Let's try to debug this issue. I can create a version with additional logging around pH query to see what value it gets. 
I'll check if it is possible to update value regardless of an actual change.

**Comment by tdragon** [comment]
I drafted a 0.3.3 version. You can install it manually or if you enable installing beta for reef-pi in HASS.
In this version I log values received from pH sensors on every update. I also increase the accuracy of pH value - this may help if your pH is too stable :)
Please try it and let me know if it helps.

**Comment by danmrossi** [comment]
Mate, apologies for the late reply, got stuck on a site with dodgy internet access for longer than expected. Back home and you sir, are a legend! its working! 

when the previous build was working, its ph never matched what was seen in reef-pi but now PERFECTO!!!

**Comment by tdragon** [comment]
I glad it helped. You can stay on the beta version - there is no other changes. I'll release it to public a bit later, still need to polish some minor things but don't have enough time.
Thank you for your report!
