### ISSUE TITLE
Add dosing usage?

### ISSUE THREAD

**Issue by Xinil** [tdragon/reef-pi-hass-custom#2]
Hello! Thanks so much for creating this easy to use HACS integration. It's working fantastic for my setup.

That said, I wonder if you'd be willing to extend the functionality a little bit? One of the APIs allows to view dosing usage information, for example:

`/api/doser/pumps/{id}/usage`

Which returns a JSON string like:

`{"current":[{"pump":11,"time":"Aug-18-14:05, 2021"}],"historical":[{"pump":11,"time":"Aug-18-14:05, 2021"}]}`

It would be great if I could pull in this information to HA so I could get a visual on my dosing runs. 

Thank you!

**Comment by tdragon** [comment]
Hello, 
Thank you :)

I'll try to add support for dosing. But I don't have a doser myself, could you provide some more data to test the implementation?
I think I'll need the following API call: `/api/doser/pumps` to discover the list of dosers.

Also what data do you need about them, is it just "time" and id?

**Comment by Xinil** [comment]
`/api/doser/pumps` returns this json below (note: I’ve got 7 ‘timers’ set up for one dosing pump.) This call really just brings back your schedules for your ‘pumps’ (times you will add liquid) to your tank, It doesn’t list the equipment pumps themselves (and we don’t need that info anyway.) The usage page is tied to each of these IDs, which are referenced in the `/usage` {id} param.


```[{"id":"1","name":"Nano Alk 7:30pm","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"19","minute":"30","second":"0","week":"*","month":"*"},"duration":15,"speed":20}},{"id":"2","name":"Nano  Alk 10pm, 17s","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"22","minute":"5","second":"0","week":"*","month":"*"},"duration":17,"speed":20}},{"id":"3","name":"Nano Alk 12am, 17s","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"0","minute":"5","second":"0","week":"*","month":"*"},"duration":17,"speed":20}},{"id":"4","name":"Nano Alk 2am, 17s","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"2","minute":"5","second":"0","week":"*","month":"*"},"duration":17,"speed":20}},{"id":"5","name":"Nano Alk 4am","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"4","minute":"5","second":"0","week":"*","month":"*"},"duration":15,"speed":20}},{"id":"6","name":"Nano Alk 6am","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"6","minute":"5","second":"0","week":"*","month":"*"},"duration":15,"speed":20}},{"id":"7","name":"Nano Alk 8am","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"8","minute":"5","second":"0","week":"*","month":"*"},"duration":15,"speed":20}},{"id":"8","name":"Nano Alk 1am","jack":"1","pin":0,"regiment":{"enable":true,"schedule":{"day":"*","hour":"1","minute":"5","second":"0","week":"*","month":"*"},"duration":15,"speed":20}}]```

Ideally from the usage call I think the important info is under the `current`  associative index, with `time` and `pump`. The `pump` data is a seconds representation for how long the dose pump ran. The `historical` associative index seems to group all pump runs from a single day.

**Comment by tdragon** [comment]
We do need the `/api/doser/pumps` to get `{id}` parameter for `/usage` call.
Are you sure that the `pump` is duration? Could you provide an example of `/api/doser/pumps/1/usage` call response from your setup?

Honestly, I am a bit confused, how to represent this data in HA in a useful way. I need to create one or more entities that can have value and set of attributes. 
One way is to create a separate entity for every "id" from `/api/doser/pumps`. It will show user friendly name from the `name` field. The value could be the `time` from `usage` call. But I am not sure how to present it on a dashboard.

Another way is to group all "pumps" based on "jack" and "pin" properties. The value could be the most recent time among all `usage` results. This way you'll have just one entity, but without a user friendly name.

**Comment by Xinil** [comment]
`/api/doser/pumps/1/usage` is returning:
```{"current":[{"pump":11,"time":"Aug-18-14:05, 2021"},{"pump":15,"time":"Aug-18-19:30, 2021"},{"pump":15,"time":"Aug-19-19:30, 2021"},{"pump":15,"time":"Aug-20-19:30, 2021"},{"pump":15,"time":"Aug-21-19:30, 2021"},{"pump":15,"time":"Aug-22-19:30, 2021"},{"pump":15,"time":"Aug-23-19:30, 2021"}],"historical":[{"pump":26,"time":"Aug-18-14:05, 2021"},{"pump":15,"time":"Aug-19-19:30, 2021"},{"pump":15,"time":"Aug-20-19:30, 2021"},{"pump":15,"time":"Aug-21-19:30, 2021"},{"pump":15,"time":"Aug-22-19:30, 2021"},{"pump":15,"time":"Aug-23-19:30, 2021"}]}```

The `pump` is how many seconds I've set it to dose for, which is 15.

Another example, my `2` pump at `/api/doser/pumps/2/usage` which I have set for 17 seconds, returns: 
```{"current":[{"pump":17,"time":"Aug-18-22:05, 2021"},{"pump":17,"time":"Aug-19-22:05, 2021"},{"pump":17,"time":"Aug-20-22:05, 2021"},{"pump":17,"time":"Aug-21-22:05, 2021"},{"pump":17,"time":"Aug-22-22:05, 2021"}],"historical":[{"pump":17,"time":"Aug-18-22:05, 2021"},{"pump":17,"time":"Aug-19-22:05, 2021"},{"pump":17,"time":"Aug-20-22:05, 2021"},{"pump":17,"time":"Aug-21-22:05, 2021"},{"pump":17,"time":"Aug-22-22:05, 2021"}]}```

> Another way is to group all "pumps" based on "jack" and "pin" properties. The value could be the most recent time among all usage results. This way you'll have just one entity, but without a user friendly name.

This honestly sounds like the best strategy to represent in HA. I have multiple 'pumps', which are just different seconds/times to pump for the one dosing chemical (Alkalinity.)

**Comment by tdragon** [comment]
Thank you for the examples! 
I'll try to implement this approach this week.

**Comment by tdragon** [comment]
Hi, 
I've implemented the logic for pumps support: it is released as 0.1.4. 
It seems to work. Could you try to install it on your setup and let me know if it works for you?
Any ideas for improvement are welcome!

**Comment by Xinil** [comment]
Seems to be working well!

![image](https://user-images.githubusercontent.com/1168011/131433032-bbaad6cc-872b-416b-ba99-c49a326223e2.png)

I'm not sure it's the 'best' way to display the data, but it's certainly a great first pass at it, and tells me what I want to know (when I dosed.) It could be improved by also telling me how long I dosed, but I'm not sure if that's a shortcoming of the history card?

**Comment by tdragon** [comment]
Thank you for feedback!
It actually has the information about duration of dosing: there is "duration" attribute.
I am not sure how to display it using standard cards, but it is visible if you click on sensor and expand attributes:
![image](https://user-images.githubusercontent.com/1210261/131459150-6f2830a2-45ed-460c-8114-082aba6a96a0.png)
