### ISSUE TITLE
Dosers

### ISSUE THREAD

**Issue by danmrossi** [tdragon/reef-pi-hass-custom#21]
Hi there @tdragon Hope all is well with you :)

Integration has been working great! Just wondering if it is humanly possible to integrate the full or close to the full dosing api into Home Assistant? As i (in a nutshell) would love to be able to fully control and automate components by combination of either reef-pi and home assistant for controlling, scheduling, dosing etc and then use a combination macros in reef-pi and automations in Home Assistant that if x doser runs longer than x then to initiate a shutdown and notify message/sound etc etc.

Hope that makes sense :)

I am more than happy to donate to your beer or coffee fund :)

**Comment by tdragon** [comment]
Hi!
Thank you for the idea, but currently I don't have any capacity to work on this project. I'll keep this ticket open, but cannot give any estimate when I can work on it.

**Comment by danmrossi** [comment]
That would be awesome thanks, totally understand :)

Sent from my iPhone

On 7 May 2023, at 4:47 am, Dmitrii ***@***.***> wrote:

﻿

Hi!
Thank you for the idea, but currently I don't have any capacity to work on this project. I'll keep this ticket open, but cannot give any estimate when I can work on it.

**Comment by danmrossi** [comment]
Hey @tdragon just thought I’d touch base and hope you are doing well, just asking if you have had any chance to look at integrating the dosing component?

**Comment by danmrossi** [comment]
Hi @tdragon just seeing if you have had any time to have a look at this
