### ISSUE TITLE
Ability to toggle/disable reef-pi-hass-custom ph data extraction 

### ISSUE THREAD

**Issue by danmrossi** [tdragon/reef-pi-hass-custom#26]
Hi @tdragon @alex255 

first of all apologies for the long read - I’ve spent a year trying everything possible to diagnose and fix this myself.

Was wondering if it’s possible to code in the ability to disable your Home Assistant add-on from even pulling or even looking at reef-pi PH data?

Unfortunately I am of the belief that this has to be done at your app level as disabling the ph entity in Home Assistant that your addon brings in has no effect as obviously your addon is still accessing the data.

The issue I have been having and others have had in various posts I’ve seen on reef2reef and other forums is that when your addon is installed into Home Assistant and configured to connect to reef-pi, the ph section drops readings as shown below
![image](https://github.com/tdragon/reef-pi-hass-custom/assets/50608357/9bb3f6bb-39e5-4dd3-8845-c993eac803a7)

it even shows the same in the reef-pi user interface as well. 

I am running reef-pi 6.0 on a Robo tank board with a rpi4 plugged into it and using the Robo tank inbuilt ph module and also a bog 
Standard plain Jane raspberry pi 4 and connected an atlas ph probe and its isolated board directly to it. Both have same issues.0

If I enable mqtt in reef-pi and map the ph into configuration.yaml to bring in ph that way while your addon is installed and connected to both reef-pi’s the readings still drop as per screenshot above.

If I remove your addon from Home assistant and wether or not I leave the mqtt enabled or not the ph readings in both reef-pi’s go back to normality in reef-pi and for the mqtt entity mapped into Home Assistant.

If I installed the addon again the ph readings drop again. Regardless if mqtt is on or not.

Also it doesn’t matter how often I configure reef-pi to get readings from the probe. Makes no difference when your addon is configured to connect to reef-pi

id like to keep using your addon so I can run macros and control outlets etc but I don’t know myself how to even compile my own version of your addon to remove the ph stuff

are you able to assist?

many thanks 

Daniel

**Comment by tdragon** [comment]
Thank you for your report.
I'll try to do something about it, but not sure when I have time. I cannot test it myself as I don't have PH sensors at the moment.

It is also linked to the reef-pi issue https://github.com/reef-pi/reef-pi/issues/1977 (unfortunately it is closed).

**Comment by danmrossi** [comment]
Hi Dmitrii

I am more than happy to test code for you in my Home Assistant

Sent from my iPhone

On 18 Apr 2024, at 8:31 PM, Dmitrii ***@***.***> wrote:

﻿

Thank you for your report.
I'll try to do something about it, but not sure when I have time. I cannot test it myself as I don't have PH sensors at the moment.

It is also linked to the reef-pi issue reef-pi/reef-pi#1977<https://github.com/reef-pi/reef-pi/issues/1977> (unfortunately it is closed).

**Comment by tdragon** [comment]
@danmrossi Please try to install pre-release 0.3.8: There is a option to disable Ph sensor updates:
![image](https://github.com/tdragon/reef-pi-hass-custom/assets/1210261/8c4a71c4-ee4c-4f8c-a869-c9f15134c647)
![image](https://github.com/tdragon/reef-pi-hass-custom/assets/1210261/561a7762-b1a4-44f1-a84a-5cc1fb85e03e)

**Comment by tdragon** [comment]
@danmrossi Hi
Did you have a chance to try the pre-release version? 
Did it help with the Ph issue?
In my setup it is running just fine, so I am thinking to publish it.

**Comment by danmrossi** [comment]
I’ve installed it today and yes so far soo good!
Sent from my iPhone

On 20 Apr 2024, at 12:26 AM, Dmitrii ***@***.***> wrote:

﻿

@danmrossi<https://github.com/danmrossi> Hi
Did you have a chance to try the pre-release version?
Did it help with the Ph issue?
In my setup it is running just fine, so I am thinking to publish it.
