### ISSUE TITLE
Another 3 Deprecations have popped up

### ISSUE THREAD

**Issue by danmrossi** [tdragon/reef-pi-hass-custom#31]
Hello @tdragon @alex255 hope you are all well :)

Running latest version of Home Assistant as of 11th December 2024 and noticed in my HA logs the following items being deprecated - I do utilise the "Lights" function of reef-pi to control lights and pumps.

If and when you get a chance :)

Logger: homeassistant.components.light
Source: components/light/__init__.py:1329
integration: Light (documentation, issues)
First occurred: 9:20:07 AM (8 occurrences)
Last logged: 9:20:07 AM

Entity None (<class 'custom_components.reef_pi.light.ReefPiLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 1> and color modes, please create a bug report at https://github.com/tdragon/reef-pi-hass-custom/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

and

Logger: homeassistant.components.light
Source: components/light/__init__.py:1276
integration: Light (documentation, issues)
First occurred: 9:20:07 AM (8 occurrences)
Last logged: 9:20:07 AM

None (<class 'custom_components.reef_pi.light.ReefPiLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/tdragon/reef-pi-hass-custom/issues

and

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 9:20:06 AM (1 occurrences)
Last logged: 9:20:06 AM

Config was used from reef_pi, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'reef_pi' custom integration

**Comment by danmrossi** [comment]
anyone?

**Comment by danmrossi** [comment]
Thanks, has it only been released as beta? As my Home Assistant HACS isn’t showing any updates for the Reef-Pi Integration?

Sent from my iPhone

On 17 Dec 2024, at 1:26 am, Dmitrii ***@***.***> wrote:

﻿

@danmrossi<https://github.com/danmrossi> Should be fixed in 0.3.11, please check

**Comment by danmrossi** [comment]
Took a little while to appear - Actually looks like this is the only “error” that appears now:

2024-12-17 07:36:16.214 WARNING (MainThread) [homeassistant.components.light] light.roboctrl_test_channel_1 (<class 'custom_components.reef_pi.light.ReefPiLight'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/tdragon/reef-pi-hass-custom/issues

Sent from my iPhone

On 17 Dec 2024, at 1:26 am, Dmitrii ***@***.***> wrote:

﻿

@danmrossi<https://github.com/danmrossi> Should be fixed in 0.3.11, please check

**Comment by tdragon** [comment]
@danmrossi Thanks for testing, 0.3.12 should fix the last warning.

**Comment by danmrossi** [comment]
Hey I have just tested it and all good now! Many many thanks for all your efforts! Hope you have a great Christmas and new years!

Sent from my iPhone

On 18 Dec 2024, at 2:59 am, Dmitrii ***@***.***> wrote:

﻿

@danmrossi<https://github.com/danmrossi> Thanks for testing, 0.3.12 should fix the last warning.

**Comment by tdragon** [comment]
@danmrossi Thank you! Have a great Christmas!
