### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by swisschris104** [tdragon/reef-pi-hass-custom#8]
I I have tried setting up both manually and via HACS. It appears I am getting a authentication error 

the following error is appearing in smart assistant:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.0.222', port=80): Max retries exceeded with url: **/auth/signin** (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa730422a60>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by tdragon** [comment]
This looks like a network or configuration problem. The integration tries to send an http request to your reef pi, but host is not reachable. 
Check that the ip address and port are correct.
Then try to ping your reef pi from Home assistant machine.

**Comment by swisschris104** [comment]
Oh god, your right. I spent hours wondering like what am I doing wrong. The ip of my pi was 192.168.0.22. I kept adding a extra 2. I was able to get the intergration loaded. Thanks for making this public. It is super useful! 

![image](https://user-images.githubusercontent.com/95115628/143781610-3d9b0aad-d8f9-4751-a1c3-5d18808ab415.png)
